version: '3'
services:
  app:
    image: docker.dev.ulang.jp/pocket-money/docker/app
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:pass@db:3306
    ports:
      - 3000:3000
    volumes:
      - ./:/pocketMoney
      - /etc/localtime:/etc/localtime:ro
  db:
    image: mysql:8.0.0
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./tmp:/work
      - /etc/localtime:/etc/localtime:ro
volumes:
  mysql-data:
    driver: local
